- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup
    
    - name: Create profile vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_hostnames: yes
        dns_support: yes
        tenancy: default
        state: "{{state}}"
      register: vpc_out
    
    - debug: 
        var: vpc_out
    
    - name: Create Public subnet 1 in Zone 1
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpc_out.vpc.id}}"
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        map_public: yes
        tags:
          Name: PubSub1
      register: PubSub1_out
    
    - name: Create Public subnet 2 in Zone 2
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpc_out.vpc.id}}"
        cidr: "{{PubSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        map_public: yes
        tags:
          Name: PubSub2
      register: PubSub2_out

    - name: Create Public subnet 3 in Zone 3
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpc_out.vpc.id}}"
        cidr: "{{PubSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        map_public: yes
        tags:
          Name: PubSub3
      register: PubSub3_out
    
    - name: Create Private subnet 1 in Zone 1
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpc_out.vpc.id}}"
        cidr: "{{PrivSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        tags:
          Name: PrivateSub1
      register: PrivateSub1_out

    - name: Create Private subnet 2 in Zone 2
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpc_out.vpc.id}}"
        cidr: "{{PrivSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        tags:
          Name: PrivateSub2
      register: PrivateSub2_out

    - name: Create Private subnet 3 in Zone 3
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{vpc_out.vpc.id}}"
        cidr: "{{PrivSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        tags:
          Name: PrivateSub3
      register: PrivateSub3_out

    - name: Create IGW for VPC
      ec2_vpc_igw:
        vpc_id: "{{vpc_out.vpc.id}}"
        state: "{{state}}"
        region: "{{region}}"
        tags:
            Name: ansible-IGW
      register: igw_out

    - debug: 
        var: igw_out